Feature/merge changes
Lumedic/ssi-mobile-sdk pull request #29
Opened 2021-06-11 11:54 UTC by kkamyczek

2021-06-11 12:10 UTC, fedyiv requested changes

2021-06-11 12:10 UTC, fedyiv commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.version      = "1.0.0"
Can we have version to be 0.0.1 ? I think it is too immature for now

2021-06-11 12:10 UTC, fedyiv commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.summary      = "Kotlin Multiplatform"
please also change summary, description and homepage and license to something meaningful

2021-06-11 12:10 UTC, fedyiv commented on samples/swiftIosApp/Podfile
>      pod 'kotlin_multiplatform_agent', :path => '../../'
Can alternative pod path pointing to some url be added here? I suggest to also leave *path* in order to allow local development. Local one should be commented out by default.

2021-06-11 12:10 UTC, fedyiv commented on samples/testIosApp/Podfile
> +source 'https://github.com/CocoaPods/Specs.git'
Can we have only one sample ios app? Otherwise it can mislead people

2021-06-11 12:10 UTC, fedyiv commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.description  = ""
Can also README be updated to reflect changes for ios artifact?

2021-06-11 12:37 UTC, kkamyczek commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.version      = "1.0.0"
I will try

2021-06-11 12:37 UTC, kkamyczek commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.summary      = "Kotlin Multiplatform"
Updated

2021-06-11 12:38 UTC, kkamyczek commented on samples/swiftIosApp/Podfile
>      pod 'kotlin_multiplatform_agent', :path => '../../'
Yes

2021-06-11 12:38 UTC, kkamyczek commented on samples/testIosApp/Podfile
> +source 'https://github.com/CocoaPods/Specs.git'
Merged

2021-06-11 12:48 UTC, kkamyczek commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.description  = ""
Could you tell me what I should add to README, please?

2021-06-15 11:30 UTC, kkamyczek commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.description  = ""
Done

2021-06-15 12:44 UTC, fedyiv commented on Specs/ssi_agent/1.0.0/ssi_agent.podspec
> +    s.description  = ""
Hi Krzysztof,
I think sections "Add multiplatform kotlin library to your app" and "Instruction for kotlin multiplatform library user to use the library in swift app" must be merged together, because currently they contradict each other.

Would you be able to combine them in one section please?

2021-06-15 12:44 UTC, fedyiv commented on run.sh
> +./gradlew :"BuildDevice" -PXCODE_CONFIGURATION=Release
Sorry, I think my previous comment for this file was not saved somehow.

Can this file can be renamed to something meaningful, so that one could understand what it is doing? For example it can be called "build_ios_artifact.sh" or something like that

2021-06-15 13:01 UTC, kkamyczek commented on run.sh
> +./gradlew :"BuildDevice" -PXCODE_CONFIGURATION=Release
done

2021-06-15 13:02 UTC, kkamyczek commented
All comments considered in

2021-06-15 13:13 UTC, fedyiv approved these changes

2021-06-15 13:21 UTC, merged