Remove deprecated method, add readme how to configure phones
Lumedic/ssi-mobile-sdk pull request #33
Opened 2021-06-23 09:21 UTC by kkamyczek

2021-06-23 09:34 UTC, fedyiv requested changes

2021-06-23 09:34 UTC, fedyiv commented on README.md
> +## Supported android devices APIs 24, 28, 29, 30:
Why 25, 26, 27 is not included?

2021-06-23 09:34 UTC, fedyiv commented on README.md
> +<img src="docs/android/Allow_all_files.png" alt="docs/android/Allow_all_files" style="zoom:30%;" />
So which permission we need "Allow access to media only" or "Allow management of all files" ?

2021-06-23 09:34 UTC, fedyiv commented on samples/androidApp/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
Can corresponding changes to be made to Android Test as well?

2021-06-23 09:34 UTC, fedyiv commented on README.md
> +## Setup permissions for API 30 - make it manually on the phone
Is there any way to request those permissions automatically?
Or at least automatically open the system screen requesting permissions?

We can provide an instruction on how to grant permissions to developers but it can not provide such instructions for the end users

2021-06-23 11:05 UTC, kkamyczek commented on README.md
> +## Supported android devices APIs 24, 28, 29, 30:
Added, and tested 25-27

2021-06-23 11:06 UTC, kkamyczek commented on README.md
> +<img src="docs/android/Allow_all_files.png" alt="docs/android/Allow_all_files" style="zoom:30%;" />
"Allow management of all files", cleaned

2021-06-23 11:06 UTC, kkamyczek commented on README.md
> +## Setup permissions for API 30 - make it manually on the phone
I will work on it

2021-06-23 15:01 UTC, kkamyczek commented on README.md
> +## Setup permissions for API 30 - make it manually on the phone
Done

2021-06-24 09:39 UTC, kkamyczek commented on samples/androidApp/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
Yep, did it

2021-06-24 10:33 UTC, fedyiv reviewed
Please fix merge conflicts also

2021-06-24 10:33 UTC, fedyiv commented on samples/androidApp/app/src/main/java/com/dxc/ssi/sample/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= 30 && !hasAllFilesPermission()) {
Krzysztof, 
it seems we need to combine this logic with  "PermissionManager.requestPermissionsIfNeeded(this, this)" call. Otherwise the logic is spread across different places

2021-06-24 10:35 UTC, kkamyczek commented on samples/androidApp/app/src/main/java/com/dxc/ssi/sample/MainActivity.kt
> +        if (Build.VERSION.SDK_INT >= 30 && !hasAllFilesPermission()) {
yep, I will clean it

2021-06-24 13:55 UTC, fedyiv approved these changes

2021-06-24 13:58 UTC, merged